[package]
name = "invoicy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
genpdf = { version = "0.2.0", features = ["images"] }
whoami = "1.5.1"
image = "0.25.1"
